spring:
  config:
    import: optional:secrets.properties  # ✅ 加载你的 secrets 文件
  application:
    name: MentalHealthSystem
  datasource:
    url: jdbc:mysql://localhost:3306/mental_health_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  mail:
    host: smtp.qq.com
    username: 2042837972@qq.com
    password: onqnaetsocliccjc
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.cupk.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 8080
  servlet:
    context-path: /mental

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}
    url: https://api.deepseek.com/v1/chat/completions

questionnaire:
  file: classpath:questionnaires/default_questionnaire.json
  assessment:
    prompt: "根据以下问卷答案，提供一个心理健康评估报告：\n\n{{answers}}\n\n请给出综合评估，建议和改善方向。"
